#!/bin/bash

## RFE::
# 0. backup /etc/passwd, if it ever
#     changes, rm it & replace with backup
# 1. check for immutables
# 2. $(tee) where .bash_history goes
# 3. who/when used sudo (auth.log)
# 4. 

# grep -v false /etc/passwd |cut -f1 -d ':'

# passwd -l <user> // lock
# passwd -u <user> // unlock
# passwd -S <user> // status

#am I root?
if [ "$(id -u)" != "0" ]; then
   echo "try sudo, br0" 1>&2
   exit 1
fi

source $(dirname $0)/checkPasswds
