#!/bin/bash

#null passwords, anyone?
USERS="$(cut -d: -f 1 /etc/passwd)"
for u in $USERS; do
    passwd -S $u | grep -Ew "NP" >/dev/null
    if [ $? -eq 0 ]; then
	echo $u
	passwd -l $u
    fi
done

#no root login
if [ -f /etc/ssh/sshd_config ]; then
    sed -ie 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
fi
