#!/bin/bash

## RFE:: should only echo the kill't person once

source $(dirname $0)/ascii

while : ; do
    for dude in $(who |cut -f1 -d " " |uniq); do
	if [ $dude != $USER ]; then
            echo "$(rando)" |write $dude 2>/dev/null
	    sudo killall -u $dude
	    echo "kill't $dude"
	fi
    done
done
