#!/bin/bash

## am I root?
if [ "$(id -u)" != "0" ]; then
   echo "try sudo, br0" 1>&2
   exit 1
fi

RULES="$(dirname $0)/brickWall"

echo -e "\nCurrent Policies/Defaults"
iptables --list |grep policy
echo ""

## debugging
echo "ya testin' shit? [Y/n] "
read -s -n 1 key
if [ "$key" = "" -o "$key" = "y" ]; then
    sed 's/DROP/REJECT/g' "${RULES}" &>/dev/null
    echo -e "ye shall be reject'd\n"
else
    sed 's/REJECT/DROP/g' "${RULES}" &>/dev/null
    echo -e "gettin' dropped like a box of rocks\n"
fi

## set default policies
echo "Change Default Policies? [N/y] "
read -s -n 1 key1
if [ "$key1" = "y" ]; then
    POLICY="${$(iptables --list |grep policy |cut -f4 -d " ")%?}"
    echo "${POLICY}"

    case "${POLICY}" in 
	ACCEPT) 
	    iptables -P INPUT DROP
	    iptables -P FORWARD DROP
	    iptables -P OUTPUT DROP ;;
	DROP) 
	    iptables -P INPUT ACCEPT
	    iptables -P FORWARD ACCEPT
	    iptables -P OUTPUT ACCEPT ;;
	*)
	    echo -e "\n${POLICY} policy unknown\n" ;;
    esac
elif [ "$key1" != "" -o "$key" != "n" ]; then
    echo -e "fuck, wrong input, br0\n"
    exit 1
fi

bash "${RULES}"
